/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Image from "next/image";
import { motion, useScroll, useTransform } from "framer-motion";
import { useState } from "react";
import { Tab } from "@headlessui/react";
import Slider from "react-slick";
import { data } from "../data/skills";

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function Home() {
  const { scrollY } = useScroll();
  const y1 = useTransform(scrollY, [0, 500], [0, -100]);
  const y2 = useTransform(scrollY, [0, 300], [0, 80]);
  const dataSkills = data.skills;
  const dataDesignSkills = data.designSkills;

  const upDownAnimation = {
    visible: {
      y: [0, -20, 20],
      transition: { delay: 2, yoyo: Infinity },
    },
  };

  const leftRightAnimation = {
    visible: {
      x: [0, -20, 3],
      transition: { delay: 2, yoyo: Infinity },
    },
  };

  // slider setting
  const settings = {
    infinite: true,
    slidesToShow: 5,
    slidesToScroll: 1,
    initialSlide: 0,
    autoplay: true,
    speed: 2000,
    autoplaySpeed: 2000,
    cssEase: "linear",
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 2,
          infinite: true,
          dots: true,
        },
      },
      {
        breakpoint: 600,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          initialSlide: 2,
        },
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
        },
      },
    ],
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>

      <main>
        <div className="continer header-page h-[100vh] w-full static overflow-hidden">
          <div
            style={{ backgroundImage: "url('/assets/background4.png')" }}
            className=" w-full h-full bg-cover relative"
          >
            <motion.div style={{ y: y2, x: 0 }}>
              <div className="absolute hidden md:block">
                <img src="/assets/bg-2.png" />
              </div>
            </motion.div>

            <div className="w-full h-full grid place-content-center absolute md:grid-cols-2">
              <div className="md:block grid place-content-center md:pr-12">
                <motion.div variants={leftRightAnimation} animate='visible'>
                <h1 className=" md:ml-auto text-8xl text-white w-fit">
                  Welcome, to
                </h1>
                </motion.div>
              </div>
              <div className="md:text-left text-center md:pl-12">
              <motion.div variants={leftRightAnimation} animate='visible'>
                <h1 className=" text-8xl text-white w-fit">My Website</h1>
                </motion.div>
              </div>
            </div>

            <motion.div style={{ y: y1, x: 0 }} >
              <div className="absolute w-[100vw] hidden md:block">
                <img src="/assets/bg-3.png" className="w-full" />
              </div>
            </motion.div>
          </div>
        </div>

        {/* introduction */}
        <div className=" w-full h-[100vh] overflow-hidden bg-[#2E0249]">
          <div className=" grid md:grid-cols-2 w-full h-full md:p-16 mt-12">
            <div className=" relative">
              <div className=" absolute w-full text-center text-white">
                <p className="text-2xl font-bold text-yellow-300">
                  Hello, My Name is
                </p>
                <h1 className=" text-8xl font-bold ">
                  PRIANDY <br /> DWI <br /> HANDIKA
                </h1>
              </div>
              <div className=" w-full overflow-hidden">
                <img
                  src="/assets/me.png"
                  className="mix-blend-multiply contrast-200 mx-auto md:h-[50em] md:absolute left-[-7] bottom-10"
                />
              </div>
            </div>

            <div>
              <div className="w-full text-center text-white">
                <p className="text-2xl font-bold">Im,</p>
                <h1 className=" text-8xl font-bold ">
                  <p className="text-yellow-300">FRONT-END</p> DEVELOPER.
                </h1>
                <p>
                  I like to craft solid and scalable frontend products with
                  great user experience
                </p>

                <div className=" grid grid-cols-2 mt-16 gap-8 px-8">
                  <p className="text-justify">
                    I can make your website responsive and I really like the
                    design and implementation of a website
                  </p>
                  <p className=" text-justify text-yellow-300">
                    I'm a junior frontend website developer and I really like
                    working in a team
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* skills section */}
        <div className=" md:h-[100vh] w-full bg-[#2E0249] md:px-32 md:py-10 ">
          <div className="md:border w-full h-full rounded-lg">
            <Tab.Group>
              <div className=" grid grid-cols-12 h-full">
                <div className=" col-span-1 h-full w-full grid place-content-center">
                  <h1 className=" m-auto text-3xl text-white font-bold -rotate-90">
                    SKILLS
                  </h1>
                </div>

                <Tab.Panels className={"col-span-10 px-20"}>
                  {/* panel frontend */}
                  <Tab.Panel className={"w-full h-full text-white pt-4"}>
                    <h1 className=" text-5xl text-center text-yellow-500">
                      FRONTEND
                    </h1>
                    <div className=" mt-[12%]">
                      <Slider {...settings}>
                        {dataSkills?.slice(0, 6).map((item, index) => (
                          <div key={index}>
                            <div className=" w-28 h-28 overflow-hidden">
                              <img src={item.image} />
                            </div>
                          </div>
                        ))}
                      </Slider>

                      <Slider {...settings} className="mt-10">
                        {dataSkills?.slice(6).map((item, index) => (
                          <div key={index}>
                            <div className=" w-28 h-28 overflow-hidden">
                              <img src={item.image} />
                            </div>
                          </div>
                        ))}
                      </Slider>
                    </div>
                  </Tab.Panel>

                  {/* panel Design */}
                  <Tab.Panel>
                    <h1 className=" text-5xl text-center text-yellow-500 mt-5">
                      DESIGN
                    </h1>
                    <div className=" mt-[20%]">
                      <Slider {...settings}>
                        {dataDesignSkills?.map((item, index) => (
                          <div key={index}>
                            <div className=" w-28 h-28 overflow-hidden">
                              <img src={item.image} />
                            </div>
                          </div>
                        ))}
                      </Slider>
                    </div>
                  </Tab.Panel>
                </Tab.Panels>

                <Tab.List
                  className={
                    "col-span-1 w-full h-full grid place-content-center"
                  }
                >
                  <div className=" grid grid-rows-3 h-[20em] min-h-[10em]  gap-3 ">
                    <Tab
                      className={({ selected }) =>
                        classNames(
                          "w-1 h-full rounded-lg bg-yellow",
                          "ring-white ring-opacity-60 ",
                          selected
                            ? "bg-white shadow bg-yellow-500"
                            : "text-blue-100 bg-yellow-100 hover:bg-white/[0.12] hover:text-white"
                        )
                      }
                    ></Tab>

                    <Tab
                      className={({ selected }) =>
                        classNames(
                          "w-1 h-full rounded-lg bg-yellow",
                          "ring-white ring-opacity-60",
                          selected
                            ? "bg-white shadow bg-yellow-500"
                            : "text-blue-100 bg-yellow-100 hover:bg-white/[0.12] hover:text-white"
                        )
                      }
                    ></Tab>

                    <Tab
                      className={({ selected }) =>
                        classNames(
                          "w-1 h-full rounded-lg bg-yellow",
                          "ring-white ring-opacity-60 ",
                          selected
                            ? "bg-white shadow bg-yellow-500"
                            : "text-blue-100 bg-yellow-100 hover:bg-white/[0.12] hover:text-white"
                        )
                      }
                    ></Tab>
                  </div>
                </Tab.List>
              </div>
            </Tab.Group>
          </div>
        </div>

        {/* Qualification section */}

        <div className=" h-[100vh] bg-[#2E0249] py-14 font-bold relative">
          <h1 className=" text-white text-5xl text-center">QUALIFICATION</h1>
          <p className=" text-yellow-300 text-lg text-center ">
            My Study Journey
          </p>
          <div className="">
            <div className="md:w-[50%]  m-auto mt-7 relative flex h-full">
              <div className=" w-[50%]">
                <motion.div variants={upDownAnimation} animate="visible">
                  <div className=" grid place-content-center rounded-lg text-2xl bg-white text-black border w-60 h-28 before:content-[''] before:w-8 before:h-8 before:bg-white before:absolute before:rotate-45 before:left-56 before:top-10 md:after:left-[20rem] after:left-[19rem] after:rounded-full after:top-9 after:w-10 after:h-10 after:absolute after:z-20 after:content-[''] after:bg-yellow-300 ">
                    SMAN 56 JakBar
                  </div>
                </motion.div>
              </div>
              <div>
                <div className="border-r-8 h-full"></div>
              </div>
            </div>

            <div className=" md:w-[50%]  m-auto relative flex">
              <div className="w-[50%] ml-auto flex">
                <div className=" mr-auto">
                  <div className="border-l-8 h-full "></div>
                </div>
                <motion.div variants={leftRightAnimation} animate="visible">
                  <div className="block">
                    <div className="text-center grid place-content-center rounded-lg text-2xl bg-white text-black ml-auto border w-60 h-28 before:content-[''] before:w-8 before:h-8 before:bg-white before:absolute before:rotate-45 before:right-56 before:top-10 ">
                      PPKD JAKBAR
                    </div>
                  </div>
                </motion.div>
              </div>
            </div>

            <div className="md:w-[50%]  m-auto relative flex h-full">
              <div className=" w-[50%]">
                <motion.div variants={upDownAnimation} animate="visible">
                  <div className="text-center grid place-content-center rounded-lg text-2xl bg-white text-black border w-60 h-28 before:content-[''] before:w-8 before:h-8 before:bg-white before:absolute before:rotate-45 before:left-56 before:top-10 md:after:left-[20rem] after:left-[19rem] after:rounded-full after:top-9 after:w-10 after:h-10 after:absolute after:z-20 after:content-[''] after:bg-yellow-300 ">
                    Esa Unggul University
                  </div>
                </motion.div>
              </div>
              <div>
                <div className="border-r-8 h-full"></div>
              </div>
            </div>

            <div className=" md:w-[50%]  m-auto relative flex">
              <div className="w-[50%] ml-auto flex">
                <div className=" mr-auto">
                  <div className="border-l-8 h-full "></div>
                </div>
                <motion.div variants={leftRightAnimation} animate="visible">
                  <div className="block">
                    <div className="text-center grid place-content-center rounded-lg text-2xl bg-white text-black ml-auto border w-60 h-28 before:content-[''] before:w-8 before:h-8 before:bg-white before:absolute before:rotate-45 before:right-56 before:top-10 ">
                    Alterra Academy x Kampus Merdeka
                    </div>
                  </div>
                </motion.div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
